// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBisFhqkMOqVGu1nUGi34OvO3WUoy7fhEc',
    appId: '1:966012427101:web:db3e6c350cad51cc0126b4',
    messagingSenderId: '966012427101',
    projectId: 'pushnotificationdemo-a2388',
    authDomain: 'pushnotificationdemo-a2388.firebaseapp.com',
    storageBucket: 'pushnotificationdemo-a2388.firebasestorage.app',
    measurementId: 'G-V2N476Y70W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqvQxeCbynhj4RXyGcUEjIolyS7rHkic',
    appId: '1:966012427101:android:c2ab43889a068e410126b4',
    messagingSenderId: '966012427101',
    projectId: 'pushnotificationdemo-a2388',
    storageBucket: 'pushnotificationdemo-a2388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSLHej5I02qGIG4kDa_iwi8rmIJNKjMPs',
    appId: '1:966012427101:ios:100441968225a8570126b4',
    messagingSenderId: '966012427101',
    projectId: 'pushnotificationdemo-a2388',
    storageBucket: 'pushnotificationdemo-a2388.firebasestorage.app',
    iosBundleId: 'com.example.prozync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSLHej5I02qGIG4kDa_iwi8rmIJNKjMPs',
    appId: '1:966012427101:ios:100441968225a8570126b4',
    messagingSenderId: '966012427101',
    projectId: 'pushnotificationdemo-a2388',
    storageBucket: 'pushnotificationdemo-a2388.firebasestorage.app',
    iosBundleId: 'com.example.prozync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBisFhqkMOqVGu1nUGi34OvO3WUoy7fhEc',
    appId: '1:966012427101:web:b244a7f0387f20580126b4',
    messagingSenderId: '966012427101',
    projectId: 'pushnotificationdemo-a2388',
    authDomain: 'pushnotificationdemo-a2388.firebaseapp.com',
    storageBucket: 'pushnotificationdemo-a2388.firebasestorage.app',
    measurementId: 'G-TL17HFR0YH',
  );
}
